### PR TITLE
Update to spdlog 1.12.0

### PR DESCRIPTION
**Pull request by helmesjo**
* Changes package versions to `1.12.0-a.0.z`.
* Updates `upstream/` to `v1.12.0`.
* Updates `fmt` to `^10.1.1`.

### CODE REVIEW

**Comment by helmesjo** [comment]
Seems like `fmt` `>=10` needs this fix: https://github.com/conda-forge/librmm-feedstock/pull/58

So will down it again.

**Comment by Klaim** [comment]
Before merging this, I just noticed https://github.com/build2-packaging/spdlog/issues/19 , I was not notified of that issue and @Wmbat doesnt seem to be available these days, so it would be best to do this fix, release a revision of 1.11.0 and then base this PR on that fix.
I'll try to do it soon but can't guarantee when yet.

**Comment by Klaim** [comment]
Meanwhile, LGTM, except the version name which is set to alpha, I'm not sure why?

**Comment by helmesjo** [comment]
> Meanwhile, LGTM, except the version name which is set to alpha, I'm not sure why?

Figured once it is merged we'll just do a `bdep release`. Didn't want to have tags created before it was merged.
If I'm not mistaken `bdep` wants it to be a snapshot when running the release command?

**Comment by Klaim** [comment]
> > Meanwhile, LGTM, except the version name which is set to alpha, I'm not sure why?
> 
> Figured once it is merged we'll just do a `bdep release`. Didn't want to have tags created before it was merged. If I'm not mistaken `bdep` wants it to be a snapshot when running the release command?

Yes it's ok to not have a tag and indeed ideally the tag should be created jsut before publishing.
But you dont need to tag if you know the version of upstream already and want to be able to adjust before tagging,
so you can set the proper version in the manifest, send to `bdep ci` as much as you want and iterate from that.
Then when it's looking good, you `bdep release --tag --push` so that the release commit and the tag gets created and pushed on the repo. Then you publish that version through `bdep publish`.
At least that's what I usually do.

But no problem if you want to wait for the release to switch to non-alpha, I guess it's leading to the same result.

**Comment by helmesjo** [comment]
Alright, thanks for the explanation. Then I'll keep it as is then you/me can just release publish once it's merged.

Speaking of CI:
https://ci.stage.build2.org/@1c546498-6536-4bb4-8d74-707b56a4452f

**Comment by helmesjo** [comment]
Queued a new build after rebasing on main (with #19):
https://ci.stage.build2.org/@a5efcd34-6b24-4ee0-a79b-d36c1060c371

**Review by Klaim — APPROVED** [review]
LGTM!

**Pull request merged**
