### PR TITLE
Port of spdlog to v1.11.0

### PR DESCRIPTION
**Pull request by Wmbat**
[ci](https://ci.cppget.org/@fe808fc5-367e-4d3b-ab0c-85ac293e047a)

### CODE REVIEW

**Comment by Klaim** [comment]
Looks like `formatter-bench.exe` is waiting for specific input. Probably some testscript have to be updated following upstream changes.

**Review by Klaim — APPROVED** [review]

**Comment by Wmbat** [comment]
The CI is still failing: https://ci.cppget.org/@57c6f5f0-49fe-4d3d-a739-727c1d2bae15
I'm not sure why it's not accepting the input of "all" that i'm passing through the testscript i added. Do you any idea of what i did wrong ?

@Klaim

**Comment by Klaim** [comment]
Looks like it should work... I'll have to check locally.

**Comment by Klaim** [comment]
There seems to be issues with the symlinks on windows, Ill fix these first.

**Comment by Klaim** [comment]
I can reproduce the issue now, will attempt a fix.

**Comment by Klaim** [comment]
Ok the issue was that the testscript was not recognized as such. `testscript` files need to either be named `testscript` or have the `.testscript` extension. Fixing that seems to run the benchmark as expected.

**Comment by Klaim** [comment]
I just launched a ci request: https://ci.stage.build2.org/@04f3e9c2-4263-4e3f-8fa8-01aa5585f70b

**Comment by Klaim** [comment]
Welp looks like something else is wrong...

**Comment by Wmbat** [comment]
we're getting configuration errors now:
```
error: unable to import target spdlog%lib{spdlog}
```
There is some problems when fetching the spdlog with git submodules

**Comment by Klaim** [comment]
Can you reproduce the issue locally? I can't.

I suspect there might be an issue with the test-packages relationships.

**Comment by Wmbat** [comment]
I can't reproduce it either

**Comment by Klaim** [comment]
I tried to simplify the fix I did on the symlinks but that's not it: https://ci.stage.build2.org/@31d93a0e-bd43-450c-9bef-76de48d69fed

**Comment by Wmbat** [comment]
I updated the package manifest file because i noticed that google-bench was no longer in "testing" but "stable".

CI: https://ci.cppget.org/@6cb41d52-e04c-403b-aa18-129ea371696b

**Comment by Wmbat** [comment]
@Klaim The CI results of my last changes seem pretty good. What do you think of it ?
I see it having trouble with mingw and emcc but otherwise, this looks quite good to me

**Comment by Klaim** [comment]
Looks like the tests are randomly failing or not? Macos/Gcc seems to segfault, that might suggests some memory usage error so maybe making sure the upstream implementation is supposed to be tested correctly might be necessary.

**Comment by Klaim** [comment]
IF the issues are from the original code, I guess we can publish the package or wait for a fixed version. If we publish it we can always revise or wait to publish the fixed version too.

**Review by EmilRosenquist — APPROVED** [review]
I accidentally made the "update" without seeing this pull request (#18). But as @Klaim pointed out this already existed. 

I tested this and it works. I think unless we want to patch this release with the upstream pull-request that fixed the include (https://github.com/gabime/spdlog/pull/2545). This is good go!

**Comment by Klaim** [comment]
LGTM

> I think unless we want to patch this release with the upstream pull-request that fixed the include (https://github.com/gabime/spdlog/pull/2545).

If we realize this is necessary we can always publish a revision for the same version.

**Pull request merged**
